package com.tonycorreia.pricepulsebackend.application.receiptanalysis

/**
 * Opaque identifier created and persisted by the orchestration before any possible call to
 * [ReceiptAnalysisProviderPort] -- never generated by the port or by a provider. See
 * receiptanalysis-slice-report.md 6.10.13.3.
 */
@JvmInline
value class ReceiptAnalysisAttemptId(val value: String) {
    init {
        require(value.isNotBlank()) { "ReceiptAnalysisAttemptId must not be blank" }
    }
}
